### PR TITLE
Moved in ReallyAbortInst method from yast2-network

### PR DESCRIPTION
**Pull request by mchf**
The method is going to be removed from yast2-network as it is no longer
used there.

http://github.com/yast/yast-network/pull/1221/

### CODE REVIEW

**Comment by teclator** [comment]
Just miss version bump and changelog entry.

**Comment by mchf** [comment]
> Just miss version bump and changelog entry.

I have no bug number for that just a consequence of removing unreferenced methods from yast2-network

**Comment by teclator** [comment]
It is fine to be merged without it but then I guess we should not merge the yast/yast-network/pull/1221 until this one reach TW at least

**Comment by mchf** [comment]
> It is fine to be merged without it but then I guess we should not merge the [yast/yast-network/pull/1221](https://github.com/yast/yast-network/pull/1221) until this one reach TW at least

it is no problem for me .... the yast2-network PR has been here for 3 weeks already, so another couple of weeks makes no difference from my POV

**Review by teclator — APPROVED** [review]
LGTM

**Comment by dgdavid** [comment]
Just for the record, looks like this change was included in yast2-firstboot 4.4.2 in Factory / openSUSE Tumbleweed

See https://build.opensuse.org/request/show/903243

**Pull request merged**
